kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-istio-api-access
  namespace: pipelines-demo
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: pipelines-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-istio