kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-istio
rules:
  - verbs:
      - '*'
    apiGroups:
      - networking.istio.io
    resources:
      - '*'