apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  selfLink: /apis/maistra.io/v1/namespaces/istio-system/servicemeshmemberrolls/default
  resourceVersion: '41249583'
  name: default
  uid: fac42671-17a1-11ea-b656-12ab2f008c5f
  creationTimestamp: '2019-12-05T20:58:25Z'
  generation: 9
  namespace: istio-system
  ownerReferences:
    - apiVersion: maistra.io/v1
      kind: ServiceMeshControlPlane
      name: basic-installdemo
      uid: 2ac15b26-17a1-11ea-ab24-0ee93b952e79
  finalizers:
    - maistra.io/istio-operator
spec:
  members:
    - bookinfo
    - servicemesh-app
    - foo-service
    - servicemeshdemo
    - pipelines-demo
status:
  configuredMembers:
    - servicemeshdemo
    - bookinfo
    - servicemesh-app
    - foo-service
  meshGeneration: 5
  meshReconciledVersion: 1.0.4-2.el8-5
  observedGeneration: 9
